import { atom, selector } from "recoil";

type Display = {
  videoList: string[];
  currentVideo: string | null;
  shaderList: string[];
  currentShader: string;
  bpm: number;
  front: string;
  youtubeVideoId: string | null;
};

const videoListTemp = [
  "/assets/0211_grid.mp4",
  "/assets/0211_Sphere1.mp4",
  "/assets/0211_Sphere2.mp4",
  "/assets/0212_9tile.mp4",
  "/assets/0212_Randam Ball.mp4",
  "/assets/0213_Circle Particle.mp4",
  "/assets/0214_CircleTunnel.mp4",
  "/assets/0214_kurage.mp4",
  "/assets/0214_line ball.mp4",
  "/assets/0214_line wave.mp4",
  "/assets/0214_SquareTunnel.mp4",
  "/assets/0214_Tunnel.mp4",
  "/assets/0214_wave.mp4",
  "/assets/0214_wave2.mp4",
  "/assets/0229_hisi grid.mp4",
  "/assets/0229_Square.mp4",
  "/assets/0301_cube1 in.mp4",
  "/assets/0301_cube1.mp4",
  "/assets/0301_cube2.mp4",
  "/assets/0301_cube3.mp4",
  "/assets/0406_prime_cube.mp4",
  "/assets/0406_wave.mp4",
  "/assets/0507_cube 1.mp4",
  "/assets/0521_dm1.mp4",
  "/assets/0521_dm2.mp4",
  "/assets/0522_dot ball.mp4",
  "/assets/0522_hexloop.mp4",
  "/assets/0522_hexloop2.mp4",
  "/assets/0522_hexloop3.mp4",
  "/assets/0522_hexloop_roll.mp4",
  "/assets/0525_Re cube1.mp4",
  "/assets/0602_cir1.mp4",
  "/assets/0603_cir2.mp4",
  "/assets/0605_LineX1.mp4",
  "/assets/0605_tenzi.mp4",
  "/assets/ANGULAR.mp4",
  "/assets/aquahall.mp4",
  "/assets/archimedes.mp4",
  "/assets/atommy.mp4",
  "/assets/base ten.mp4",
  "/assets/base_ten.mp4",
  "/assets/BEEPLE-SETTING_SUN.mp4",
  "/assets/BestTen-DOT.otf",
  "/assets/BOKK.mp4",
  "/assets/BOX_BEAT.mp4",
  "/assets/breath_ctrl.mp4",
  "/assets/brokchrd.mp4",
  "/assets/building_tubes.mp4",
  "/assets/built.ee.mp4",
  "/assets/CLEANROOM.mp4",
  "/assets/crystmounts.mp4",
  "/assets/Cube 1.mp4",
  "/assets/Cube 2.mp4",
  "/assets/CUTTT.mp4",
  "/assets/cycloid.mp4",
  "/assets/darknet.mp4",
  "/assets/dirty_ribbon.mp4",
  "/assets/domeshards.mp4",
  "/assets/DVDE.mp4",
  "/assets/exhaust.mp4",
  "/assets/farkedpattern.mp4",
  "/assets/FIBER_OPTICAL.mp4",
  "/assets/firegrid.mp4",
  "/assets/fireworks.mp4",
  "/assets/gerschwinn.mp4",
  "/assets/glass_ladder.mp4",
  "/assets/glaubox.mp4",
  "/assets/glytchghost.mp4",
  "/assets/GOBO.v2.mp4",
  "/assets/GOBOv2.mp4",
  "/assets/handgun.mp4",
  "/assets/HEXXX.mp4",
  "/assets/jahara.mp4",
  "/assets/kewbic_flow.mp4",

  "/assets/kosendj-glitch-1wash1ma.mp4",
  "/assets/kosendj-glitch-furaji.mp4",
  "/assets/kosendj-glitch-HARUKAZE.mp4",
  "/assets/kosendj-glitch-HolyGrail.mp4",
  "/assets/kosendj-glitch-HRKZ_PT.mp4",
  "/assets/kosendj-glitch-nikuzuki.mp4",
  "/assets/kosendj-glitch-unasuke.mp4",
  "/assets/kosendj-glitch-いわしま.mp4",
  "/assets/kosendj-glitch-にく.mp4",
  "/assets/kosendj-glitch-はるかぜ.mp4",
  "/assets/kosendj-logo-flip.mp4",
  "/assets/kosendj-logo-earth-2.mp4",
  "/assets/kosendj-earth-only.mp4",
  "/assets/kosendj-nikuzuki-tbs.mp4",
  // "/assets/kosendj-logo.png",
  "/assets/membrane.mp4",
  "/assets/meta_build.mp4",
  "/assets/milkcave.mp4",
  "/assets/moar.mp4",
  "/assets/mocircshii.mov",
  "/assets/mocircshii.mp4",
  "/assets/MOONVIRUS.mp4",
  "/assets/narrow_gultch.mp4",
  "/assets/octmesh.mp4",
  "/assets/OKKKK.mp4",
  "/assets/p-crawl.mp4",
  "/assets/pewpy_dollar_sign.mp4",
  "/assets/pink_vynil.mp4",
  "/assets/plugs_slower.mp4",
  "/assets/poley-two.mp4",
  "/assets/PRAY_STATE.mp4",
  "/assets/rainbee.mp4",
  "/assets/rebalance.mp4",
  "/assets/rolling.mp4",
  "/assets/scream.mp4",
  "/assets/space_crystals.mp4",
  "/assets/splick.mp4",
  "/assets/Square Rotation.mp4",
  "/assets/STEPS.mp4",
  "/assets/STRT.mp4",
  "/assets/t-hawk.mp4",
  "/assets/Tech 1.mp4",
  "/assets/Tech 2.mp4",
  "/assets/Tech 3.mp4",
  "/assets/Tech Cube 1.mp4",
  "/assets/Tech Cube 2.mp4",
  "/assets/Tech Sphere.mp4",
  "/assets/tech.fux.mp4",
  "/assets/TENDRIL.mp4",
  "/assets/tracerfaun.mp4",
  "/assets/trianglefield_two.mp4",
  "/assets/triangle_field.mp4",
  "/assets/tunnal.mp4",
  "/assets/twirlers.mp4",
  "/assets/twisted_hall.mp4",
  "/assets/ubersketch_preview.mp4",
  "/assets/UNPLUG.mp4",
  "/assets/warm_neon_birth.mp4",
  "/assets/Wire Cube 1.mp4",
  "/assets/Wire Cube 2.mp4",
  "/assets/Wire Cube 3.mp4",
  "/assets/worm_parade.mp4",
  "/assets/WRMMM.mp4",
  "/assets/XANNN.mp4",
];

const shaderList = [
  // "uvGradient",
  // "rainbow",
  "glitch",
  "pixelate",
  "rgbGlitch",
  "rgbShift",
  "halftone",
  "none",
];

export const displayState = atom<Display>({
  key: "displayState",
  default: {
    videoList: videoListTemp,
    currentVideo: videoListTemp[0],
    shaderList: shaderList,
    currentShader: shaderList[0],
    bpm: 120,
    front: "tile",
    youtubeVideoId: null,
  },
});

export const displayStateSelector = selector<Display>({
  key: "displayStateSelector",
  get: ({ get }) => {
    get(displayState);
  },
  set: ({ set }, newValue) => {
    localStorage.setItem("displayStateSelector", JSON.stringify(newValue));
    set(displayState, newValue);
  },
});
